'use strict';
// Geometry in metres, independent from the DOM and the rendering loop.
const Arch=(()=>{
 const EPS=1e-7,copy=o=>JSON.parse(JSON.stringify(o)),cross=(a,b,c)=>(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x),distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
 const polygon=z=>z.vertices||[{x:z.x,z:z.z},{x:z.x+z.w,z:z.z},{x:z.x+z.w,z:z.z+z.d},{x:z.x,z:z.z+z.d}];
 const signed=p=>p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a.x*b.z-b.x*a.z;},0)/2,area=p=>Math.abs(signed(p));
 const bounds=p=>({x:Math.min(...p.map(v=>v.x)),z:Math.min(...p.map(v=>v.z)),w:Math.max(...p.map(v=>v.x))-Math.min(...p.map(v=>v.x)),d:Math.max(...p.map(v=>v.z))-Math.min(...p.map(v=>v.z))});
 function onSegment(p,a,b){return Math.abs(cross(a,b,p))<EPS&&p.x>=Math.min(a.x,b.x)-EPS&&p.x<=Math.max(a.x,b.x)+EPS&&p.z>=Math.min(a.z,b.z)-EPS&&p.z<=Math.max(a.z,b.z)+EPS;}
 function intersection(a,b,c,d){const x=b.x-a.x,z=b.z-a.z,u=d.x-c.x,v=d.z-c.z,den=x*v-z*u;if(Math.abs(den)<EPS)return null;const t=((c.x-a.x)*v-(c.z-a.z)*u)/den,s=((c.x-a.x)*z-(c.z-a.z)*x)/den;return t>=-EPS&&t<=1+EPS&&s>=-EPS&&s<=1+EPS?{x:a.x+t*x,z:a.z+t*z}:null;}
 function validatePolygon(p){if(!Array.isArray(p)||p.length<3||p.length>60)throw Error('Une pièce doit avoir entre 3 et 60 sommets.');p.forEach((v,i)=>{if(!Number.isFinite(v.x)||!Number.isFinite(v.z)||Math.abs(v.x)>100||Math.abs(v.z)>100)throw Error('Coordonnée de sommet invalide.');if(distance(v,p[(i+1)%p.length])<.05)throw Error('Un côté de pièce doit mesurer au moins 5 cm.');});for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){if(j===i+1||(i===0&&j===p.length-1))continue;const a=p[i],b=p[(i+1)%p.length],c=p[j],d=p[(j+1)%p.length];if(intersection(a,b,c,d)||onSegment(a,c,d)||onSegment(c,a,b))throw Error('Les côtés de la pièce se croisent.');}if(area(p)<.04)throw Error('Surface de pièce trop petite.');return p.map(v=>({x:+v.x,z:+v.z}));}
 function contains(p,q){let yes=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if(onSegment(q,a,b))return true;if((a.z>q.z)!==(b.z>q.z)&&q.x<(b.x-a.x)*(q.z-a.z)/(b.z-a.z)+a.x)yes=!yes;}return yes;}
 function convexOverlap(a,b){for(const p of[a,b])for(let i=0;i<p.length;i++){const x=p[(i+1)%p.length].z-p[i].z,z=p[i].x-p[(i+1)%p.length].x,aa=a.map(v=>v.x*x+v.z*z),bb=b.map(v=>v.x*x+v.z*z);if(Math.min(Math.max(...aa),Math.max(...bb))-Math.max(Math.min(...aa),Math.min(...bb))<1e-5)return false;}return true;}
 function clip(subject,clipper){let output=subject;const sign=Math.sign(signed(clipper));for(let i=0;i<clipper.length;i++){const a=clipper[i],b=clipper[(i+1)%clipper.length],input=output;output=[];for(let j=0;j<input.length;j++){const p=input[j],q=input[(j+1)%input.length],dp=sign*cross(a,b,p),dq=sign*cross(a,b,q);if(dp>=-EPS)output.push(p);if((dp>=0)!==(dq>=0)){const t=dp/(dp-dq);output.push({x:p.x+t*(q.x-p.x),z:p.z+t*(q.z-p.z)});}}if(!output.length)break;}return output;}
 function triangles(p){return THREE.ShapeUtils.triangulateShape(p.map(v=>new THREE.Vector2(v.x,v.z)),[]).map(t=>t.map(i=>p[i]));}
 function overlapArea(a,b){let total=0;for(const t of triangles(a))for(const u of triangles(b)){const p=clip(t,u);if(p.length>=3)total+=area(p);}return total;}
 const envelope=[{x:0,z:0},{x:21,z:0},{x:21,z:25},{x:15,z:25},{x:15,z:14},{x:0,z:14}];
 function intervals(p,x){const zs=[];for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];if((a.x<x)!==(b.x<x))zs.push(a.z+(x-a.x)*(b.z-a.z)/(b.x-a.x));}zs.sort((a,b)=>a-b);const out=[];for(let i=0;i+1<zs.length;i+=2)out.push([zs[i],zs[i+1]]);return out;}
 function unionArea(polys,outline=envelope){const all=[...polys,outline],xs=all.flatMap(p=>p.map(v=>v.x)),edges=all.flatMap(p=>p.map((a,i)=>[a,p[(i+1)%p.length]]));for(let i=0;i<edges.length;i++)for(let j=i+1;j<edges.length;j++){const p=intersection(...edges[i],...edges[j]);if(p)xs.push(p.x);}const xx=[...new Set(xs.map(x=>+x.toFixed(8)))].sort((a,b)=>a-b);let sum=0;for(let i=1;i<xx.length;i++){const x=(xx[i]+xx[i-1])/2,env=intervals(outline,x),spans=polys.flatMap(p=>intervals(p,x)).flatMap(([a,b])=>env.map(([c,d])=>[Math.max(a,c),Math.min(b,d)])).filter(([a,b])=>b>a).sort((a,b)=>a[0]-b[0]);let length=0,end=-Infinity;for(const[a,b]of spans){length+=Math.max(0,b-Math.max(a,end));end=Math.max(end,b);}sum+=length*(xx[i]-xx[i-1]);}return sum;}
 const nodeKey=(x,z)=>'p_'+x.toFixed(5)+'_'+z.toFixed(5);
 function normalizeWall(w){return {n1:String(w.n1||nodeKey(w.x1,w.z1)),n2:String(w.n2||nodeKey(w.x2,w.z2)),axis:['x','z','free'].includes(w.axis)?w.axis:'free',fixedLength:w.fixedLength==null?null:+w.fixedLength};}
 function checkConstraints(s){const nodes=new Map();for(const w of s.walls){for(const k of[1,2]){const id=w['n'+k],p={x:w['x'+k],z:w['z'+k]};if(!/^[\w.:-]{1,100}$/.test(id))throw Error('Identifiant de jonction invalide.');if(nodes.has(id)&&distance(nodes.get(id),p)>.0001)throw Error('Les extrémités liées doivent partager la même position.');nodes.set(id,p);}if(w.axis==='x'&&Math.abs(w.z2-w.z1)>.0001||w.axis==='z'&&Math.abs(w.x2-w.x1)>.0001)throw Error('La contrainte horizontale/verticale du mur est incompatible.');if(w.fixedLength!==null&&(!Number.isFinite(w.fixedLength)||w.fixedLength<.1||Math.abs(Math.hypot(w.x2-w.x1,w.z2-w.z1)-w.fixedLength)>.001))throw Error('Ce déplacement modifierait une longueur verrouillée.');}for(const z of s.zones)if(z.nodes){if(z.nodes.length!==polygon(z).length)throw Error('Jonctions de pièce invalides.');z.nodes.forEach((id,i)=>{if(nodes.has(id)&&distance(nodes.get(id),polygon(z)[i])>.0001)throw Error('La pièce et ses murs liés ne coïncident pas.');});}}
 function propagate(before,next){
  // Independent equality graphs for X and Z. Orthogonal walls constrain a coordinate,
  // shared endpoints constrain both. Fixed lengths are checked atomically afterwards.
  const parents={x:new Map(),z:new Map()},find=(axis,id)=>{const m=parents[axis];if(!m.has(id))m.set(id,id);if(m.get(id)!==id)m.set(id,find(axis,m.get(id)));return m.get(id);},join=(axis,a,b)=>parents[axis].set(find(axis,a),find(axis,b));
  next.walls.forEach(w=>{Object.assign(w,normalizeWall(w));if(w.axis==='x')join('z',w.n1,w.n2);if(w.axis==='z')join('x',w.n1,w.n2);});
  const requests={x:new Map(),z:new Map()},oldNodes=new Map();before.walls.forEach(w=>[1,2].forEach(k=>oldNodes.set(w['n'+k]||nodeKey(w['x'+k],w['z'+k]),{x:w['x'+k],z:w['z'+k]})));
  function request(id,axis,value){const key=find(axis,id),prev=requests[axis].get(key);if(prev!==undefined&&Math.abs(prev-value)>.0001)throw Error('Contraintes incompatibles : libérez un axe ou déliez la jonction.');requests[axis].set(key,value);}
  next.walls.forEach(w=>[1,2].forEach(k=>{const id=w['n'+k],old=oldNodes.get(id);if(old)for(const axis of['x','z'])if(Math.abs(old[axis]-w[axis+k])>EPS)request(id,axis,w[axis+k]);}));
  next.zones.forEach((z,i)=>{const old=z.nodes?before.zones.find(a=>a.nodes&&a.nodes.join('|')===z.nodes.join('|')):null;if(z.nodes&&old){const a=polygon(old),b=polygon(z);if(a.length===b.length)z.nodes.forEach((id,j)=>{for(const axis of['x','z'])if(Math.abs(a[j][axis]-b[j][axis])>EPS)request(id,axis,b[j][axis]);});}});
  const nodes=new Map();next.walls.forEach(w=>[1,2].forEach(k=>{const id=w['n'+k];for(const axis of['x','z']){const v=requests[axis].get(find(axis,id));if(v!==undefined)w[axis+k]=v;}nodes.set(id,{x:w['x'+k],z:w['z'+k]});}));
  next.zones.forEach(z=>{if(z.nodes){z.vertices=polygon(z).map((p,i)=>copy(nodes.get(z.nodes[i])||p));Object.assign(z,bounds(z.vertices));}});
 }
 function footprint(f,margin=0){const c=Math.cos(f.r||0),s=Math.sin(f.r||0);return[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,z])=>({x:f.x+x*(f.w/2+margin)*c+z*(f.d/2+margin)*s,z:f.z-x*(f.w/2+margin)*s+z*(f.d/2+margin)*c}));}
 function wallRect(w,a=0,b=Math.hypot(w.x2-w.x1,w.z2-w.z1)){const L=Math.hypot(w.x2-w.x1,w.z2-w.z1),u=(w.x2-w.x1)/L,v=(w.z2-w.z1)/L;return[[a,-1],[b,-1],[b,1],[a,1]].map(([d,s])=>({x:w.x1+u*d-v*w.t/2*s,z:w.z1+v*d+u*w.t/2*s}));}
 function solidWallParts(w,f){const L=Math.hypot(w.x2-w.x1,w.z2-w.z1);if(f.y>=w.h-.001)return[];const gaps=(w.op||[]).filter(o=>f.y>=o.sill-.001&&f.y+f.h<=o.sill+o.h+.001).sort((a,b)=>a.d-b.d);const parts=[];let cursor=0;for(const o of [...gaps,{d:L,w:0}]){const b=o.d-o.w/2;if(b-cursor>.001)parts.push(wallRect(w,cursor,b));cursor=o.d+o.w/2;}return parts;}
 function doorSectors(w,o){if(!['porte','double'].includes(o.type))return[];const L=Math.hypot(w.x2-w.x1,w.z2-w.z1),u=(w.x2-w.x1)/L,v=(w.z2-w.z1)/L,side=o.swing===-1?-1:1;return(o.type==='double'?[0,1]:[o.hinge==='right'?1:0]).map(right=>{const r=o.type==='double'?o.w/2:o.w,origin=o.d+(right?1:-1)*o.w/2,points=[{x:origin,z:side*(w.t/2+.015)}];for(let i=0;i<=18;i++){const a=i*Math.PI/36;points.push({x:origin+(right?-1:1)*r*Math.cos(a),z:side*(w.t/2+.015+r*Math.sin(a))});}return points.map(p=>({x:w.x1+u*p.x-v*p.z,z:w.z1+v*p.x+u*p.z}));});}
 function collisions(s,margin=.6){const hard=[],clear=[],doors=[],shapes=s.furniture.map(f=>footprint(f)),expanded=s.furniture.map(f=>footprint(f,f.clearance??margin)),vertical=(a,b)=>Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>.001;
  s.furniture.forEach((f,i)=>{for(let j=i+1;j<s.furniture.length;j++){if(!vertical(f,s.furniture[j]))continue;if(convexOverlap(shapes[i],shapes[j]))hard.push({a:i,b:j,text:`${f.n} ↔ ${s.furniture[j].n}`});else if(convexOverlap(expanded[i],shapes[j])||convexOverlap(expanded[j],shapes[i]))clear.push({a:i,b:j,text:`${f.n} ↔ ${s.furniture[j].n}`});}
   s.walls.forEach((w,wi)=>{const parts=solidWallParts(w,f);if(parts.some(p=>convexOverlap(shapes[i],p)))hard.push({a:i,wall:wi,text:`${f.n} ↔ mur ${wi+1}`});else if(parts.some(p=>convexOverlap(expanded[i],p)))clear.push({a:i,wall:wi,text:`${f.n} ↔ mur ${wi+1}`});});
   (s.building?.columns||COLUMNS.map(([x,z])=>({x,z,w:.45,d:.45,h:H}))).forEach(({x,z,w,d,h},ci)=>{if(f.y>=h)return;const p=footprint({x,z,w,d,r:0});if(convexOverlap(shapes[i],p))hard.push({a:i,column:ci,text:`${f.n} ↔ poteau ${ci+1}`});else if(convexOverlap(expanded[i],p))clear.push({a:i,column:ci,text:`${f.n} ↔ poteau ${ci+1}`});});
  });s.walls.forEach((w,wi)=>(w.op||[]).forEach((o,oi)=>doorSectors(w,o).forEach(p=>{s.furniture.forEach((f,i)=>{if(f.y<o.h&&convexOverlap(p,shapes[i]))doors.push({a:i,wall:wi,opening:oi,text:`Porte du mur ${wi+1} ↔ ${f.n}`});});(s.building?.columns||COLUMNS.map(([x,z])=>({x,z,w:.45,d:.45,h:H}))).forEach((c,ci)=>{if(convexOverlap(p,footprint({...c,r:0})))doors.push({wall:wi,opening:oi,column:ci,text:`Porte du mur ${wi+1} ↔ poteau ${ci+1}`});});s.walls.forEach((other,j)=>{if(wi!==j&&convexOverlap(p,wallRect(other)))doors.push({wall:wi,opening:oi,text:`Porte du mur ${wi+1} ↔ mur ${j+1}`});});})));
  return{hard,clear,doors,shapes,expanded};
 }
 function imagePoint(r,p){const a=-(r.rotation||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),x=p.x-r.x,z=p.z-r.z;return{x:(x*c-z*s)/r.scale,z:(x*s+z*c)/r.scale};}
 function calibrate(r,a,b,metres){const d=distance(a,b);if(d<2||!Number.isFinite(metres)||metres<=0)throw Error('Choisissez deux points distincts et une distance positive.');const scale=metres/d;if(Math.max(r.widthPx,r.heightPx)*scale>200)throw Error('Le plan calibré dépasserait 200 m.');return{...r,scale,calibrated:true,calibration:{a,b,metres}};}
 return{EPS,polygon,signed,area,bounds,contains,validatePolygon,intersection,convexOverlap,overlapArea,unionArea,envelope,nodeKey,normalizeWall,checkConstraints,propagate,footprint,wallRect,solidWallParts,doorSectors,collisions,imagePoint,calibrate,distance};
})();
