'use strict';
const BUNDLED_MODELS={chair:{name:'Fauteuil bois & velours',source:'https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SheenChair',credit:'Eric Chadwick / Wayfair · CC0',description:'Modèle de référence détaillé, sans référence commerciale.'},sofa:{name:'Canapé bois & cuir',source:'https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SheenWoodLeatherSofa',credit:'Fran Calvente / Poly Haven ; Eric Chadwick / DGG · CC0 / CC-BY 4.0',description:'Modèle issu de sofa_03, Poly Haven. Dimensions à confirmer.'}};
Object.assign(BUNDLED_MODELS,{"damask": {"name": "Fauteuil damassé", "source": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ChairDamaskPurplegold", "credit": "Eric Chadwick / CC-BY-4.0", "description": "Asset Khronos texturé. Dimensions ajustables."}, "velvet": {"name": "Canapé velours", "source": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/GlamVelvetSofa", "credit": "Eric Chadwick / CC-BY-4.0", "description": "Asset Khronos texturé. Dimensions ajustables."}, "pouf": {"name": "Pouf en soie", "source": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SpecularSilkPouf", "credit": "Eric Chadwick / CC-BY-4.0", "description": "Asset Khronos texturé. Dimensions ajustables."}, "fridge": {"name": "Réfrigérateur professionnel", "source": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CommercialRefrigerator", "credit": "Eric Chadwick / CC-BY-4.0 ; Sean Thomas / CC-BY-4.0", "description": "Asset Khronos texturé. Dimensions ajustables."}, "plant": {"name": "Plante en pot", "source": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/DiffuseTransmissionPlant", "credit": "Eric Chadwick / CC-BY-4.0 ; Rico Cilliers / CC0-1.0", "description": "Asset Khronos texturé. Dimensions ajustables."}});
const FURN_ASSETS={chair:"chair",sofa:"sofa",plant:"plant"};
function builtinAsset(id){const m=BUNDLED_MODELS[id];return {builtin:id,name:m.name,credit:m.credit,source:m.source};}
// Chargement de fond : chaque modèle rejoint la scène dès qu'il est prêt, sans bloquer l'atelier.
async function preloadFurniture(){for(const id of Object.values(FURN_ASSETS)){const key="asset_builtin_"+id;
 if(assetCache.has(key))continue;
 const result=await parseAsset(builtinAsset(id));result.model.userData.originalSize=result.size;assetCache.set(key,result.model);
 if(typeof requestBuild==='function')requestBuild();}}

let polygonDraft=[],archCursor=null,calibrationPoint=null,referenceTexture=null,referenceData=null,referenceLoading=null,archReport=null;
const builtinPromises=new Map();
function loadBuiltin(id){if(!BUNDLED_MODELS[id])return Promise.reject(Error('Modèle inconnu.'));if(BUNDLED_MODELS[id].data)return Promise.resolve(BUNDLED_MODELS[id].data);if(!builtinPromises.has(id))builtinPromises.set(id,new Promise((res,rej)=>{const script=document.createElement('script');script.src='editor-assets/models/'+id+'.js';script.onload=()=>res(BUNDLED_MODELS[id].data);script.onerror=()=>{builtinPromises.delete(id);rej(Error('Modèle local introuvable. Conservez le dossier editor-assets/models.'));};document.head.appendChild(script);}));return builtinPromises.get(id);}
async function assetData(asset){return asset.builtin?loadBuiltin(asset.builtin):asset.data;}
function uid(){return 'junction_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);}
// Chaque élément modifié reste indépendant : l'extrémité de mur déplacée quitte sa jonction et
// l'espace remodelé quitte ses murs, pour qu'Arch.propagate n'entraîne plus les voisins.
// Une jonction renommée par l'opération elle-même (scission, périmètre créé) est laissée intacte.
function isolateEdit(before,next){const moved=(a,b)=>Math.abs(a-b)>Arch.EPS;
 next.walls.forEach((w,i)=>{const old=before.walls[i];if(!old)return;
  for(const k of[1,2])if(w['n'+k]&&w['n'+k]===old['n'+k]&&(moved(w['x'+k],old['x'+k])||moved(w['z'+k],old['z'+k])))w['n'+k]=uid();
  if(w.axis==='x'&&moved(w.z1,w.z2)||w.axis==='z'&&moved(w.x1,w.x2))w.axis='free';});
 next.zones.forEach((z,i)=>{const old=before.zones[i];if(!z.nodes||!old?.nodes||JSON.stringify(z.nodes)!==JSON.stringify(old.nodes))return;
  if(JSON.stringify(Arch.polygon(z))!==JSON.stringify(Arch.polygon(old)))delete z.nodes;});}
function nearbyPoint(p){let best={x:snap(p.x),z:snap(p.z)},d=.18;for(const w of state.walls)for(const k of[1,2]){const q={x:w['x'+k],z:w['z'+k]},dist=Arch.distance(p,q);if(dist<d){best=q;d=dist;}}return best;}
function nodeAt(p){for(const w of state.walls)for(const k of[1,2])if(Arch.distance(p,{x:w['x'+k],z:w['z'+k]})<.0001)return w['n'+k];return Arch.nodeKey(p.x,p.z);}
function addRoomWalls(z){const p=Arch.polygon(z);z.vertices=clone(p);z.nodes=p.map(nodeAt);p.forEach((a,i)=>{const b=p[(i+1)%p.length],n1=z.nodes[i],n2=z.nodes[(i+1)%p.length];if(state.walls.some(w=>w.n1===n1&&w.n2===n2||w.n2===n1&&w.n1===n2))return;state.walls.push({...DW(a.x,a.z,b.x,b.z,'cloison',.15),n1,n2,axis:Math.abs(a.z-b.z)<.0001?'x':Math.abs(a.x-b.x)<.0001?'z':'free'});});}
function finishPolygon(){if(polygonDraft.length<3){notify('Placez au moins trois sommets.');return;}try{Arch.validatePolygon(polygonDraft);}catch(e){notify(e.message);return;}commit(()=>{const z={n:'Pièce polygonale',c:'#b7c59c',t:'',surface:'concrete',vertices:clone(polygonDraft),...Arch.bounds(polygonDraft)};state.zones.push(z);if($('roomWithWalls').checked)addRoomWalls(z);selection={kind:'zones',i:state.zones.length-1};});polygonDraft=[];setTool('select');}
function architecturePointerDown(e,p){if(e.button!==0)return false;if(tool==='polygon'){if(p){const q=nearbyPoint(p);if(polygonDraft.length>=3&&Arch.distance(q,polygonDraft[0])<.25)finishPolygon();else{polygonDraft.push(q);$('finishRoom').disabled=polygonDraft.length<3;requestBuild();}}return true;}if(tool==='calibrate'){const r=state.reference;if(!p||!r)return true;const q=Arch.imagePoint(r,p);if(q.x<0||q.z<0||q.x>r.widthPx||q.z>r.heightPx){notify('Choisissez un point sur l’image du plan.');return true;}if(!calibrationPoint){calibrationPoint=q;notify('Premier point choisi. Cliquez l’autre extrémité de la cote connue.');requestBuild();}else{const a=calibrationPoint;commit(()=>state.reference=Arch.calibrate(state.reference,a,q,Number($('referenceDistance').value)));calibrationPoint=null;setTool('select');notify('Fond de plan recalibré. La géométrie existante conserve ses dimensions.');}return true;}return false;}
function architecturePointerMove(e){if(tool==='polygon'&&polygonDraft.length){const p=floorPoint(e);archCursor=p?nearbyPoint(p):null;requestBuild();}}
function architectureCancel(){polygonDraft=[];calibrationPoint=null;archCursor=null;$('finishRoom').disabled=true;}
function architectureProperties(){const o=selected(),p=$('properties');if(!o)return;
 p.insertAdjacentHTML('beforeend','<button id="focusSelection">Cadrer la sélection</button>');$('focusSelection').onclick=()=>{let obj=selected(),kind=selection.kind;if(kind==='open'){obj=state.walls[selection.wi];kind='walls';}setView('3d');const x=kind==='zones'?obj.x+obj.w/2:kind==='walls'?(obj.x1+obj.x2)/2:obj.x,z=kind==='zones'?obj.z+obj.d/2:kind==='walls'?(obj.z1+obj.z2)/2:obj.z;if(x!==undefined){target.set(x-CX,kind==='furniture'?obj.y+obj.h/2:0,z-CZ);dist=Math.max(4,kind==='walls'?wallLength(obj)*2.5:Math.max(obj.w||1,obj.d||1,obj.h||1)*3.4);theta=.35;phi=1.05;updateCamera();}};
 if(selection.kind==='zones'){
  p.insertAdjacentHTML('beforeend','<h3>Contour &amp; murs</h3>'+`<p class="note">${Arch.area(Arch.polygon(o)).toFixed(2)} m² · ${Arch.polygon(o).length} sommets${o.nodes?' · périmètre lié aux murs':''}</p>`+(o.vertices?'<div id="vertexFields" class="fields">'+o.vertices.map((v,i)=>`<label>Sommet ${i+1} · X<input type="number" step=".05" data-vertex="${i}" data-axis="x" value="${v.x.toFixed(3)}"></label><label>Sommet ${i+1} · Z<input type="number" step=".05" data-vertex="${i}" data-axis="z" value="${v.z.toFixed(3)}"></label>`).join('')+'</div>':'<button id="convertPolygon">Éditer les sommets</button>')+'<button id="createRoomWalls">Créer / lier le périmètre</button>'+(o.nodes?'<button id="unlinkRoom">Délier la pièce des murs</button>':''));
  p.querySelectorAll('[data-vertex]').forEach(el=>el.onchange=()=>commit(()=>{o.vertices[+el.dataset.vertex][el.dataset.axis]=el.value.trim()===''?NaN:+el.value;Object.assign(o,Arch.bounds(o.vertices));}));
  if($('convertPolygon'))$('convertPolygon').onclick=()=>commit(()=>o.vertices=Arch.polygon(o));
  $('createRoomWalls').onclick=()=>commit(()=>addRoomWalls(o));if($('unlinkRoom'))$('unlinkRoom').onclick=()=>commit(()=>delete o.nodes);
 }
 if(selection.kind==='walls'){
  p.insertAdjacentHTML('beforeend','<h3>Contraintes</h3>'+`<label class="field">Axe<select id="wallAxis"><option value="free" ${o.axis==='free'?'selected':''}>Libre</option><option value="x" ${o.axis==='x'?'selected':''}>Horizontal (X)</option><option value="z" ${o.axis==='z'?'selected':''}>Vertical (Z)</option></select></label><label class="check"><input id="lockWallLength" type="checkbox" ${o.fixedLength!==null?'checked':''}> Verrouiller ${wallLength(o).toFixed(2)} m</label><label class="field">Longueur souhaitée · m<input id="wallExactLength" type="number" min=".1" step=".01" value="${wallLength(o).toFixed(3)}"></label><button id="unlinkWall">Délier les extrémités</button><p class="note">Les extrémités communes suivent le déplacement. Une longueur verrouillée incompatible annule la modification.</p>`);
  $('wallAxis').onchange=()=>commit(()=>{o.axis=$('wallAxis').value;if(o.axis==='x')o.z2=o.z1;if(o.axis==='z')o.x2=o.x1;});$('lockWallLength').onchange=()=>commit(()=>o.fixedLength=$('lockWallLength').checked?wallLength(o):null);
  $('wallExactLength').onchange=()=>commit(()=>{const n=+$('wallExactLength').value,L=wallLength(o);if(!Number.isFinite(n)||n<.1)throw Error('La longueur doit dépasser 10 cm.');o.x2=o.x1+(o.x2-o.x1)*n/L;o.z2=o.z1+(o.z2-o.z1)*n/L;});
  $('unlinkWall').onclick=()=>commit(()=>{o.n1=uid();o.n2=uid();});
 }
 if(selection.kind==='furniture'){
  p.insertAdjacentHTML('beforeend',`<h3>Dégagement autour de l’objet</h3><label class="field">Marge personnalisée · m<input id="objectClearance" type="number" min="0" max="5" step=".05" value="${o.clearance??state.clearance??.6}"></label><p class="note">Marge d’étude autour de l’encombrement, hors exigence réglementaire.</p>`+(o.type==='custom'?`<p class="note">${esc(state.assets[o.assetId]?.credit||'Modèle importé — vérifier ses dimensions et sa provenance.')}</p>`:''));$('objectClearance').onchange=()=>commit(()=>o.clearance=+$('objectClearance').value);
 }
 if(selection.kind==='open'&&['porte','double'].includes(o.type)){
  p.insertAdjacentHTML('beforeend',`<h3>Débattement à 90°</h3><label class="field">Côté d’ouverture<select id="doorSwing"><option value="1" ${o.swing!==-1?'selected':''}>Côté A du mur</option><option value="-1" ${o.swing===-1?'selected':''}>Côté B du mur</option></select></label>`+(o.type==='porte'?`<label class="field">Charnière<select id="doorHinge"><option value="left" ${o.hinge!=='right'?'selected':''}>Début de l’ouverture</option><option value="right" ${o.hinge==='right'?'selected':''}>Fin de l’ouverture</option></select></label>`:''));$('doorSwing').onchange=()=>commit(()=>o.swing=+$('doorSwing').value);if($('doorHinge'))$('doorHinge').onchange=()=>commit(()=>o.hinge=$('doorHinge').value);
 }
}
function referenceWorld(r,p){const a=r.rotation*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return{x:r.x+(p.x*c-p.z*s)*r.scale,z:r.z+(p.x*s+p.z*c)*r.scale};}
function ensureReference(){const r=state.reference;if(!r)return;if(referenceData===r.data&&referenceTexture)return;if(referenceLoading===r.data)return;referenceLoading=r.data;const img=new Image();img.onload=()=>{if(state.reference?.data!==r.data){referenceLoading=null;return;}if(referenceTexture){texturePool.delete(referenceTexture);referenceTexture.dispose();}referenceTexture=new THREE.Texture(img);referenceTexture.encoding=THREE.sRGBEncoding;referenceTexture.needsUpdate=true;texturePool.add(referenceTexture);referenceData=r.data;referenceLoading=null;requestBuild();};img.onerror=()=>{referenceLoading=null;notify('Le fond de plan ne peut pas être affiché.');};img.src=r.data;}
function architectureRebuild(){
 const r=state.reference;if(r?.visible&&view==='plan'){ensureReference();if(referenceTexture&&referenceData===r.data){const w=r.widthPx*r.scale,d=r.heightPx*r.scale,shape=new THREE.PlaneGeometry(w,d),mat=new THREE.MeshBasicMaterial({map:referenceTexture,transparent:true,opacity:r.opacity,depthWrite:false,side:THREE.DoubleSide}),m=new THREE.Mesh(shape,mat),center=referenceWorld(r,{x:r.widthPx/2,z:r.heightPx/2});m.rotation.set(-Math.PI/2,0,-r.rotation*Math.PI/180);m.position.set(center.x-CX,.075,center.z-CZ);m.renderOrder=1;helpers.add(m);}if(calibrationPoint){const p=referenceWorld(r,calibrationPoint);sphere(helpers,.12,p.x-CX,.15,p.z-CZ,new THREE.MeshBasicMaterial({color:0xdd7033}));}}
 if(polygonDraft.length){const p=[...polygonDraft,...(archCursor?[archCursor]:[])];line(p.map(v=>[v.x-CX,.18,v.z-CZ]),0x956322);polygonDraft.forEach(v=>sphere(helpers,.1,v.x-CX,.2,v.z-CZ,new THREE.MeshBasicMaterial({color:0xda9b4b})));}
 const z=selection?.kind==='zones'?selected():null;if(z?.vertices){const p=z.vertices;line([...p,p[0]].map(v=>[v.x-CX,.16,v.z-CZ]),0xb5783f);p.forEach((v,i)=>{const h=sphere(helpers,.13,v.x-CX,.22,v.z-CZ,new THREE.MeshBasicMaterial({color:0xf0b374}));h.userData.pick={kind:'vertex',i:selection.i,vi:i};if($('showDimensions').checked&&view!=='interior'){const q=p[(i+1)%p.length];dimension([v.x-CX,.16,v.z-CZ],[q.x-CX,.16,q.z-CZ],Arch.distance(v,q).toFixed(2)+' m');}});}
 archReport=Arch.collisions(state,state.clearance??.6);
 if($('showCollisions').checked){const hard=new Set(archReport.hard.flatMap(c=>[c.a,c.b]).filter(i=>i!==undefined));for(const i of hard){const p=archReport.shapes[i],f=state.furniture[i];line([...p,p[0]].map(v=>[v.x-CX,f.y+.12,v.z-CZ]),0xc63929);}}
 if($('showClearances').checked&&selection?.kind==='furniture'){const f=selected(),p=Arch.footprint(f,f.clearance??state.clearance??.6);line([...p,p[0]].map(v=>[v.x-CX,f.y+.13,v.z-CZ]),0xc48a24);}
 if($('showDoorSwings').checked&&view!=='interior')state.walls.forEach((w,wi)=>w.op.forEach((o,oi)=>Arch.doorSectors(w,o).forEach(p=>{const blocked=archReport.doors.some(c=>c.wall===wi&&c.opening===oi);line([...p,p[0]].map(v=>[v.x-CX,.12,v.z-CZ]),blocked?0xca4c2d:0x6f9370);})));dirty=true;
}
function architectureChecks(){const r=archReport||Arch.collisions(state,state.clearance??.6);$('collisionChecks').innerHTML=`<strong>${r.hard.length} collision(s) · ${r.doors.length} débattement(s) gêné(s)</strong><p class="note">${r.clear.length} proximité(s) sous la marge de ${(state.clearance??.6).toFixed(2)} m. Les marges par objet peuvent différer.</p>`+[['Collisions',r.hard],['Portes',r.doors],['Dégagements',r.clear]].map(([name,list])=>`<details ${name==='Collisions'?'open':''}><summary>${name} · ${list.length}</summary>${list.slice(0,20).map(c=>`<button class="issue" data-issue-kind="${c.a!==undefined?'furniture':'walls'}" data-issue="${c.a??c.wall}">${esc(c.text)}</button>`).join('')}${list.length>20?'<p class="note">20 premiers résultats affichés.</p>':''}</details>`).join('');$('collisionChecks').querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>select({kind:b.dataset.issueKind,i:+b.dataset.issue}));
 $('referenceStatus').textContent=state.reference?(state.reference.calibrated?'Calibré':'Échelle initiale estimée')+' · '+(state.reference.widthPx*state.reference.scale).toFixed(2)+' × '+(state.reference.heightPx*state.reference.scale).toFixed(2)+' m':'Aucun plan importé — cotes du bâtiment toujours estimées.';
 $('referenceControls').hidden=!state.reference;if(state.reference){for(const k of['x','z','rotation','opacity'])$('reference_'+k).value=state.reference[k];$('referenceVisible').checked=state.reference.visible;}
 $('globalClearance').value=state.clearance??.6;
}
async function importReference(file){if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>8*1024*1024){notify('Choisissez une image PNG, JPEG ou WebP de moins de 8 Mo.');return;}try{const data=await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(file);}),img=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=data;});if(img.width>10000||img.height>10000)throw Error('Image trop grande (10 000 pixels maximum par côté).');commit(()=>state.reference={name:file.name,data,widthPx:img.width,heightPx:img.height,x:0,z:0,scale:21/img.width,rotation:0,opacity:.85,visible:true,calibrated:false});setView('plan');notify('Plan chargé. Saisissez une distance connue, puis cliquez ses deux extrémités.');}catch(e){notify('Import du plan impossible : '+(e.message||'image invalide'));}}
function freePlacement(size){const candidates=[{x:17,z:17},{x:19,z:20},{x:17,z:15}];for(let z=1;z<25;z+=2)for(let x=1;x<21;x+=2)candidates.push({x,z});for(const p of candidates){const f={...p,w:size.x,d:size.z,h:size.y,y:0,r:0,n:'Nouveau modèle'},poly=Arch.footprint(f);if(Arch.area(poly)-Arch.overlapArea(poly,buildingOutline())>.001)continue;const i=state.furniture.length,result=Arch.collisions({walls:state.walls,furniture:[...state.furniture,f]},0);if(!result.hard.some(c=>c.a===i||c.b===i)&&!result.doors.some(c=>c.a===i))return p;}return{x:17,z:17};}
async function insertBuiltin(id){if(busy)return;busy=true;notify('Chargement du modèle détaillé…');try{const asset={builtin:id,name:BUNDLED_MODELS[id].name,credit:BUNDLED_MODELS[id].credit,source:BUNDLED_MODELS[id].source},key='asset_builtin_'+id;let result;if(assetCache.has(key)){result={model:assetCache.get(key),size:assetCache.get(key).userData.originalSize};}else result=await parseAsset(asset);result.model.userData.originalSize=result.size;busy=false;assetCache.set(key,result.model);beginPlacement({type:'custom',assetId:key,n:asset.name,r:0,y:0,w:result.size.x,h:result.size.y,d:result.size.z},{key,value:asset});}catch(e){notify('Chargement impossible : '+e.message);}finally{busy=false;}}
function architectureSetup(){
 $('drawRoom').onclick=()=>{architectureCancel();setTool('polygon');setView('plan');notify('Cliquez les sommets ; Entrée ou Fermer la pièce pour terminer.');};$('finishRoom').onclick=finishPolygon;
 $('referenceFile').onchange=e=>{importReference(e.target.files[0]);e.target.value='';};$('importReference').onclick=()=>$('referenceFile').click();$('calibrateReference').onclick=()=>{if(!state.reference){notify('Importez d’abord un fond de plan.');return;}calibrationPoint=null;setTool('calibrate');setView('plan');notify('Cliquez les deux extrémités de la distance connue.');};
 $('removeReference').onclick=()=>commit(()=>{delete state.reference;calibrationPoint=null;});for(const k of['x','z','rotation','opacity'])$('reference_'+k).onchange=()=>commit(()=>{state.reference[k]=+$('reference_'+k).value;if(k==='rotation'||k==='x'||k==='z')calibrationPoint=null;});$('referenceVisible').onchange=()=>commit(()=>state.reference.visible=$('referenceVisible').checked);
 for(const id of['showCollisions','showClearances','showDoorSwings'])$(id).onchange=rebuild;$('globalClearance').onchange=()=>commit(()=>state.clearance=+$('globalClearance').value);
 $('linkWallEnds').onclick=()=>commit(()=>{const nodes=[],remap=new Map();state.walls.forEach(w=>[1,2].forEach(k=>{const p={x:w['x'+k],z:w['z'+k]},found=nodes.find(n=>Arch.distance(n,p)<=.15);if(found){remap.set(w['n'+k],found.id);w['x'+k]=found.x;w['z'+k]=found.z;w['n'+k]=found.id;}else nodes.push({...p,id:w['n'+k]});}));state.zones.forEach(z=>{if(z.nodes)z.nodes=z.nodes.map(id=>remap.get(id)||id);});});
 $('realFurniture').innerHTML=Object.entries(BUNDLED_MODELS).map(([id,m])=>`<button data-builtin="${id}">＋ ${m.name}</button><p class="note">${m.description} <a href="${m.source}" target="_blank" rel="noopener">Source et licence</a></p>`).join('');$('realFurniture').querySelectorAll('[data-builtin]').forEach(b=>b.onclick=()=>insertBuiltin(b.dataset.builtin));
}
