'use strict';
// Le pas de déplacement survit à la reconstruction de l'inspecteur après chaque commit.
let columnStep=.25;
function buildingOutline(s=state){return s.building?.outline||Arch.envelope;}
function buildingColumns(s=state){return s.building?.columns||COLUMNS.map(([x,z])=>({x,z,w:.45,d:.45,h:H}));}
function buildingHeight(s=state){return s.building?.height??H;}
function validateBuilding(b={}){const height=num(b.height??H,.5,30,'Hauteur du bâtiment'),outline=Arch.validatePolygon(b.outline||Arch.envelope),raw=b.columns||COLUMNS.map(([x,z])=>({x,z,w:.45,d:.45,h:height}));if(!Array.isArray(raw)||raw.length>150)throw Error('Maximum 150 poteaux.');return {height,outline,columns:raw.map(c=>({x:num(c.x,-100,100,'X poteau'),z:num(c.z,-100,100,'Z poteau'),w:num(c.w,.05,5,'Largeur poteau'),d:num(c.d,.05,5,'Profondeur poteau'),h:num(c.h??height,.2,30,'Hauteur poteau')}))};}
function buildingSlab(y,depth,material,name){const outline=buildingOutline(),shape=new THREE.Shape(outline.map(v=>new THREE.Vector2(v.x-CX,-v.z+CZ))),mesh=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth,bevelEnabled:false}),material);mesh.rotation.x=-Math.PI/2;mesh.position.y=y;mesh.receiveShadow=true;mesh.name=name;world.add(mesh);return mesh;}
function buildingRoof(){const height=buildingHeight();buildingSlab(height,.15,mats.cream,'Plafond');const b=Arch.bounds(buildingOutline());for(let x=b.x+1.5;x<b.x+b.w;x+=3)for(let z=b.z+2;z<b.z+b.d;z+=4)if(Arch.contains(buildingOutline(),{x,z}))box(world,1.1,.04,.16,x-CX,height-.03,z-CZ,mats.light);}
function splitWallAt(index,t){const w=state.walls[index],L=wallLength(w),distance=L*t;if(t<=0||t>=1||distance<.1||L-distance<.1)throw Error('Jonction trop proche d’une extrémité.');if(w.fixedLength!==null)throw Error('Déverrouillez la longueur avant de scinder ce mur.');if(w.op.some(o=>Math.abs(o.d-distance)<o.w/2+.05))throw Error('La jonction traverse une ouverture.');const n=uid(),x=w.x1+(w.x2-w.x1)*t,z=w.z1+(w.z2-w.z1)*t,second={...clone(w),x1:x,z1:z,n1:n,op:w.op.filter(o=>o.d>distance).map(o=>({...o,d:o.d-distance}))};
 const oldEnd=w.n2;w.op=w.op.filter(o=>o.d<distance);w.x2=x;w.z2=z;w.n2=n;state.walls.push(second);
 for(const room of state.zones){if(!room.nodes)continue;for(let i=0;i<room.nodes.length;i++){const j=(i+1)%room.nodes.length;if(room.nodes[i]===w.n1&&room.nodes[j]===oldEnd||room.nodes[i]===oldEnd&&room.nodes[j]===w.n1){room.nodes.splice(i+1,0,n);room.vertices.splice(i+1,0,{x,z});break;}}}return {x,z,node:n};}
function buildingProperties(){
 if(selection?.kind==='columns'){const c=selected();
  $('properties').insertAdjacentHTML('beforeend','<h3>Déplacer ce poteau</h3>'
   +'<label class="check"><input id="unlockBuilding" type="checkbox" '+(lockBuilding?'':'checked')+'> Déplacer le bâti à la souris</label>'
   +'<p class="note">Coché, le poteau sélectionné se glisse dans la scène. Sinon, utilisez les coordonnées ci-dessus ou les pas ci-dessous.</p>'
   +'<div class="nudge">'+[['−X',-1,0],['+X',1,0],['−Z',0,-1],['+Z',0,1]].map(([n,dx,dz])=>'<button data-nudge="'+dx+' '+dz+'">'+n+'</button>').join('')
   +'<label class="field">Pas · m<input id="columnStep" type="number" min=".01" max="5" step=".05" value="'+columnStep+'"></label></div>'
   +'<button id="columnToCeiling">Monter jusqu’au plafond ('+buildingHeight().toFixed(2)+' m)</button>'
   +'<p class="note">Section et hauteur estimées : à relever sur site.</p>');
  $('unlockBuilding').onchange=()=>{lockBuilding=!$('unlockBuilding').checked;if($('lockBuilding'))$('lockBuilding').checked=lockBuilding;notify(lockBuilding?'Murs et poteaux protégés du déplacement à la souris.':'Bâti déverrouillé : murs et poteaux se glissent à la souris.');};
  $('columnStep').onchange=()=>{columnStep=Math.min(5,Math.max(.01,+$('columnStep').value||.25));$('columnStep').value=columnStep;};
  $('properties').querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>{const [dx,dz]=b.dataset.nudge.split(' ').map(Number);columnStep=Math.min(5,Math.max(.01,+$('columnStep').value||.25));const step=columnStep;
   commit(()=>{const c=state.building.columns[selection.i];c.x=+(c.x+dx*step).toFixed(4);c.z=+(c.z+dz*step).toFixed(4);});});
  $('columnToCeiling').onclick=()=>commit(()=>state.building.columns[selection.i].h=buildingHeight());return;}
 if(selection?.kind!=='walls')return;$('properties').insertAdjacentHTML('beforeend','<h3>Raccord de cloison</h3><label class="field">Jonction depuis le début · m<input id="splitDistance" type="number" step=".01" value="'+(wallLength(selected())/2).toFixed(2)+'"></label><button id="splitWall">Créer une jonction sur ce mur</button><p class="note">Scinde le mur sans déplacer les ouvertures. Tracez ensuite une cloison depuis cette jonction pour créer un raccord en T.</p>');$('splitWall').onclick=()=>commit(()=>splitWallAt(selection.i,+$('splitDistance').value/wallLength(selected())));}
function buildingSetup(){
 $('tab-walls').insertAdjacentHTML('beforeend','<div class="section-title">POTEAUX <button id="addColumn">＋ Ajouter</button></div><div id="columnList"></div><p class="note">Sélectionnez un poteau pour régler sa position, sa section et sa hauteur. Positions héritées de l’étude, à confirmer sur relevé.</p>');
 $('addColumn').onclick=()=>commit(()=>{const b=Arch.bounds(buildingOutline());state.building.columns.push({x:+(b.x+b.w/2).toFixed(2),z:+(b.z+b.d/2).toFixed(2),w:.45,d:.45,h:buildingHeight()});selection={kind:'columns',i:state.building.columns.length-1};});
 $('tab-walls').insertAdjacentHTML('beforeend','<details><summary>Géométrie du local</summary><p class="note">Cotes estimées. Modifier l’emprise ajuste la dalle et le plafond ; ajustez ensuite les murs existants à ce contour.</p><label class="field">Hauteur du plafond · m<input id="buildingHeight" type="number" step=".01"></label><label class="field">Contour : X Z, un sommet par ligne<textarea id="buildingOutline" rows="7"></textarea></label><label class="field">Poteaux : X Z largeur profondeur hauteur, un par ligne<textarea id="buildingColumns" rows="7"></textarea></label><button id="applyBuilding">Appliquer la géométrie</button><button id="restoreProportionsAll">Rétablir les dimensions natives de tous les modèles</button><p class="note">Les dimensions natives peuvent modifier les dégagements : vérifiez les alertes. Les positions sont conservées ; les objets verrouillés sont exclus.</p></details>');
 $('applyBuilding').onclick=()=>commit(()=>{const lines=id=>$(id).value.trim()?$(id).value.trim().split(/\n+/).map(row=>row.trim().split(/[;\s]+/).map(Number)):[];const outline=lines('buildingOutline');if(outline.some(row=>row.length!==2))throw Error('Chaque sommet attend X Z.');const columns=lines('buildingColumns');if(columns.some(row=>row.length!==5))throw Error('Chaque poteau attend X Z largeur profondeur hauteur.');state.building=validateBuilding({height:+$('buildingHeight').value,outline:outline.map(([x,z])=>({x,z})),columns:columns.map(([x,z,w,d,h])=>({x,z,w,d,h}))});});
 $('restoreProportionsAll').onclick=()=>commit(()=>{for(const f of state.furniture){if(f.locked)continue;const s=nativeSize(f);if(s)Object.assign(f,{w:s.x,h:s.y,d:s.z,lockAspect:true});}});
}
function buildingRefresh(){
 if($('columnList')){$('columnList').innerHTML=buildingColumns().map((c,i)=>`<button class="item ${selection?.kind==='columns'&&selection.i===i?'selected':''}" data-column="${i}"><span class="name">Poteau ${i+1}</span><small>${c.w.toFixed(2)} × ${c.d.toFixed(2)} m · h ${c.h.toFixed(2)}</small></button>`).join('');
  $('columnList').querySelectorAll('button').forEach(b=>b.onclick=()=>select({kind:'columns',i:+b.dataset.column}));}if($('buildingArea'))$('buildingArea').textContent=Arch.area(buildingOutline()).toFixed(1);if($('buildingHeightBadge'))$('buildingHeightBadge').textContent=buildingHeight().toFixed(2);if(!$('buildingOutline'))return;$('buildingHeight').value=buildingHeight();$('buildingOutline').value=buildingOutline().map(p=>p.x+' '+p.z).join('\n');$('buildingColumns').value=buildingColumns().map(p=>[p.x,p.z,p.w,p.d,p.h].join(' ')).join('\n');}
