'use strict';
let placementDraft=null,placementPoint=null,placementAsset=null,rotationDrag=null;
let rotationIncrement=15,repeatPlacement=false,allowOverlap=false;
const previewMaterials=[];
const objectKey=()=>'obj_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
const groupKey=()=>'group_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
function catalogSize(type){const t=FURN_TYPES[type],s=assetCache.get('asset_builtin_'+FURN_ASSETS[type])?.userData.originalSize;return s?{w:s.x,h:s.y,d:s.z,native:true}:{w:t.w,h:t.h,d:t.d,native:false};}
function furnitureIndices(){if(selection?.kind!=='furniture')return [];if(selection.indices)return [...new Set(selection.indices)].filter(i=>state.furniture[i]);const g=selected()?.groupId;return g?state.furniture.map((f,i)=>f.groupId===g?i:-1).filter(i=>i>=0):[selection.i];}
// A plain click on a member of a multi-selection keeps it, so the whole set stays draggable.
function chooseFurniture(i,toggle=false){const current=furnitureIndices();if(!toggle&&current.length>1&&current.includes(i))return;let ids=toggle?current:[];if(toggle&&ids.includes(i))ids=ids.filter(n=>n!==i);else ids.push(i);selection=ids.length?{kind:'furniture',i:ids[ids.length-1],...(toggle?{indices:ids}:{})}:null;refresh();}
function furnitureCenter(ids=furnitureIndices(),source=state){return ids.reduce((p,i)=>({x:p.x+source.furniture[i].x/ids.length,z:p.z+source.furniture[i].z/ids.length}),{x:0,z:0});}
function requireUnlocked(ids=furnitureIndices()){if(ids.some(i=>state.furniture[i].locked))throw Error('Déverrouillez les objets avant de les modifier.');}
// Le pivot reste celui de la sélection ; ce qui repose dessus suit le même mouvement rigide.
function transformFurniture(ids,source,dx=0,dz=0,angle=0){const pivot=furnitureCenter(ids,source),c=Math.cos(angle),s=Math.sin(angle);for(const i of supportedBy(ids,source)){const a=source.furniture[i],f=state.furniture[i];f.x=pivot.x+(a.x-pivot.x)*c+(a.z-pivot.z)*s+dx;f.z=pivot.z-(a.x-pivot.x)*s+(a.z-pivot.z)*c+dz;f.r=a.r+angle;}}
function rotateFurniture(angle){const ids=furnitureIndices();if(!ids.length)return;commit(()=>{requireUnlocked(ids);transformFurniture(ids,clone(state),0,0,angle);});}
function groupFurniture(){const ids=furnitureIndices();if(ids.length<2){notify('Ctrl + clic pour sélectionner plusieurs meubles.');return;}commit(()=>{requireUnlocked(ids);const id=groupKey();ids.forEach(i=>state.furniture[i].groupId=id);selection={kind:'furniture',i:ids[0]};});}
// Dupliquer emporte ce qui repose sur la sélection, avec des identifiants neufs.
function duplicateFurniture(){const ids=supportedBy(furnitureIndices());if(!ids.length)return false;commit(()=>{const gid=ids.length>1?groupKey():null,next=[],remap=new Map();
 for(const i of ids){const f=clone(state.furniture[i]),id=objectKey();remap.set(f.id,id);f.id=id;f.x+=.5;f.z+=.5;f.n+=' · copie';f.locked=false;delete f.groupId;if(gid)f.groupId=gid;next.push(state.furniture.length);state.furniture.push(f);}
 for(const i of next){const f=state.furniture[i];if(f.support&&remap.has(f.support))f.support=remap.get(f.support);}
 selection={kind:'furniture',i:next[0],indices:next};});return true;}
function deleteFurniture(){const ids=furnitureIndices();if(!ids.length)return false;commit(()=>{requireUnlocked(ids);for(const i of ids.sort((a,b)=>b-a))state.furniture.splice(i,1);selection=null;});return true;}
function editFurnitureProperty(key,value){const ids=furnitureIndices(),o=selected();requireUnlocked(ids);if(['x','z'].includes(key)){transformFurniture(ids,clone(state),key==='x'?value-o.x:0,key==='z'?value-o.z:0);return;}if(key==='degrees'){transformFurniture(ids,clone(state),0,0,value*Math.PI/180-o.r);return;}if(key==='y'){const dy=value-o.y;ids.forEach(i=>{const f=state.furniture[i];delete f.support;f.y+=dy;});return;}if(['w','h','d'].includes(key)&&o.lockAspect!==false){const ratio=value/o[key];for(const k of ['w','h','d'])o[k]*=ratio;return;}o[key]=value;}
function alignFurniture(axis){const ids=furnitureIndices();if(ids.length<2)return;commit(()=>{requireUnlocked(ids);const v=state.furniture[ids[0]][axis];ids.forEach(i=>state.furniture[i][axis]=v);});}
function distributeFurniture(axis){const ids=furnitureIndices().sort((a,b)=>state.furniture[a][axis]-state.furniture[b][axis]);if(ids.length<3){notify('Sélectionnez au moins trois meubles.');return;}commit(()=>{requireUnlocked(ids);const first=state.furniture[ids[0]][axis],last=state.furniture[ids[ids.length-1]][axis];ids.forEach((i,n)=>state.furniture[i][axis]=first+(last-first)*n/(ids.length-1));});}
function nativeSize(f){const id=f.type==='custom'?f.assetId:'asset_builtin_'+FURN_ASSETS[f.type];return assetCache.get(id)?.userData.originalSize;}
function restoreFurnitureSize(){commit(()=>{requireUnlocked();for(const i of furnitureIndices()){const f=state.furniture[i],s=nativeSize(f);if(s)Object.assign(f,{w:s.x,h:s.y,d:s.z,lockAspect:true});}});}
function beginPlacement(draft,asset=null){if(readOnlyBlocked())return;setTool('place',draft.type);placementDraft={...clone(draft),x:0,z:0,y:draft.y??0,baseY:draft.y??0,r:0,lockAspect:true};placementAsset=asset;placementPoint=null;selection=null;refresh();notify('Déplacez le curseur, puis cliquez pour poser. R : tourner · Échap : annuler.');}
function startCatalogPlacement(type){beginPlacement(catalogDraft(type));}
function placementValidity(f){const candidate={...f,x:placementPoint?.x??f.x,z:placementPoint?.z??f.z};const poly=Arch.footprint(candidate);if(Arch.area(poly)-Arch.overlapArea(poly,buildingOutline())>.001)return 'Hors de l’emprise';const i=state.furniture.length,report=Arch.collisions({...state,furniture:[...state.furniture,candidate]},0);return report.hard.some(c=>c.a===i||c.b===i)?'Collision':report.doors.some(c=>c.a===i)?'Débattement de porte':'Libre';}
// Un équipement de plateau se pose sur le meuble survolé : le brouillon monte à sa hauteur
// et garde le lien, ce qui lève aussi la fausse collision avec le meuble porteur.
function updatePlacementPoint(p){placementPoint={x:snap(p.x),z:snap(p.z)};
 if(!placementDraft)return;const mount=placementDraft.mount||mountOf(placementDraft);
 // Un objet mural se plaque au mur le plus proche du curseur et s'oriente vers la pièce.
 if(mount==='mur'){const s=wallSnap(placementDraft,p);placementDraft.onWall=!!s;if(s){placementPoint={x:s.x,z:s.z};placementDraft.r=s.r;}return;}
 const host=mount==='support'?supportAt(placementPoint):null;
 if(host){placementDraft.y=+Math.min(20,host.top).toFixed(4);placementDraft.support=host.s.id;}
 else{delete placementDraft.support;placementDraft.y=FURN_TYPES[placementDraft.type]?.y??placementDraft.baseY??0;}}
function placeDraft(p){if(!placementDraft)return;updatePlacementPoint(p);const verdict=placementValidity(placementDraft);if(verdict!=='Libre'&&!allowOverlap){notify(verdict+' — déplacez le meuble ou activez le placement libre.');requestBuild();return;}const f={...clone(placementDraft),...placementPoint},asset=placementAsset;delete f.onWall;delete f.baseY;commit(()=>{if(asset)state.assets[asset.key]=asset.value;state.furniture.push(f);selection={kind:'furniture',i:state.furniture.length-1};});if(!repeatPlacement)setTool('select');else requestBuild();}
// An imported model abandoned before it is posed must not keep its GLB in memory.
function cancelPlacement(){const pending=placementAsset;placementDraft=null;placementPoint=null;placementAsset=null;
 if(pending&&!pending.value.builtin&&!state.assets[pending.key]&&assetCache.has(pending.key)){releaseAsset(assetCache.get(pending.key));assetCache.delete(pending.key);}}
function manipulationKey(e){if(e.ctrlKey||e.metaKey||e.altKey)return false;const k=e.key.toLowerCase();if(k!=='r'&&k!==','&&k!=='.')return false;if(pointer||rotationDrag)return true;if(!placementDraft&&selection?.kind!=='furniture')return false;e.preventDefault();const angle=(k===','||e.shiftKey?-1:1)*(rotationIncrement||15)*Math.PI/180;if(placementDraft){placementDraft.r+=angle;requestBuild();}else rotateFurniture(angle);return true;}
function manipulationPointerDown(e,p){
 if(e.button!==0||e.altKey||e.shiftKey||tool==='navigate')return false;
 if(placementDraft){placeDraft(p||placementPoint||{x:0,z:0});return true;}
 const hit=pick(e);if(hit?.kind==='rotate'&&p){const ids=furnitureIndices();try{requireUnlocked(ids);}catch(err){notify(err.message);return true;}const center=furnitureCenter(ids);rotationDrag={before:snapshot(),ids,center,start:Math.atan2(p.x-center.x,p.z-center.z),angle:0};canvas.setPointerCapture(e.pointerId);return true;}
 if(e.ctrlKey&&hit?.kind==='furniture'){chooseFurniture(hit.i,true);return true;}return false;
}
function manipulationPointerMove(e){const p=floorPoint(e);if(placementDraft&&!pointer){if(p){updatePlacementPoint(p);requestBuild();}return true;}if(!rotationDrag)return false;if(!p)return true;const d=rotationDrag;let angle=Math.atan2(p.x-d.center.x,p.z-d.center.z)-d.start;angle=Math.atan2(Math.sin(angle),Math.cos(angle));if(rotationIncrement&&!e.altKey)angle=Math.round(angle/(rotationIncrement*Math.PI/180))*rotationIncrement*Math.PI/180;state=JSON.parse(d.before);transformFurniture(d.ids,clone(state),0,0,angle);d.angle=angle;requestBuild();return true;}
function endRotation(cancel=false){if(!rotationDrag)return;const d=rotationDrag;rotationDrag=null;try{if(cancel)state=JSON.parse(d.before);else{state=validate(state);record(d.before);}}catch(e){state=JSON.parse(d.before);notify(e.message);}refresh();}
function manipulationDispose(){previewMaterials.splice(0).forEach(m=>m.dispose());}
function manipulationRebuild(){
 if(placementDraft&&placementPoint){const f={...placementDraft,...placementPoint},verdict=placementValidity(f),color=verdict==='Libre'?0x559f78:0xce654b,g=furnitureModel(f),original=new Set();g.traverse(o=>{if(!o.isMesh)return;const cloneMaterial=m=>{if(!o.userData.assetShared&&!pool.has(m))original.add(m);const n=m.clone();n.transparent=true;n.opacity=.5;n.depthWrite=false;previewMaterials.push(n);return n;};o.material=Array.isArray(o.material)?o.material.map(cloneMaterial):cloneMaterial(o.material);o.castShadow=false;});original.forEach(m=>m.dispose());g.position.set(f.x-CX,f.y+.04,f.z-CZ);g.rotation.y=f.r;helpers.add(g);const p=Arch.footprint(f);line([...p,p[0]].map(v=>[v.x-CX,.1,v.z-CZ]),color);$('placementStatus').textContent=verdict+' · '+(f.r*180/Math.PI).toFixed(0)+'°'+(f.support?' · sur '+(furnitureById(f.support)?.n||'un support'):'')+((f.mount||mountOf(f))==='mur'?(f.onWall?' · contre le mur':' · approchez d’un mur'):'');}
 else if($('placementStatus'))$('placementStatus').textContent='Ctrl + clic : sélection multiple · R : rotation';
 const ids=furnitureIndices();for(const i of ids){const f=state.furniture[i],p=Arch.footprint(f);line([...p,p[0]].map(v=>[v.x-CX,f.y+.08,v.z-CZ]),0xcf8c3b);}
 if(ids.length&&view!=='interior'&&!placementDraft){const c=furnitureCenter(ids),radius=Math.max(.8,...ids.map(i=>Math.hypot(state.furniture[i].x-c.x,state.furniture[i].z-c.z)+Math.max(state.furniture[i].w,state.furniture[i].d)/2))+.4;const pts=[];for(let i=0;i<=48;i++){const a=i/48*Math.PI*2;pts.push([c.x-CX+Math.sin(a)*radius,.22,c.z-CZ+Math.cos(a)*radius]);}line(pts,0xb27932);const h=sphere(helpers,.2,c.x-CX,.22,c.z-CZ+radius,new THREE.MeshBasicMaterial({color:0xe0a34e}));h.userData.pick={kind:'rotate',i:selection.i};}
}
function manipulationProperties(){if(selection?.kind!=='furniture')return;const ids=furnitureIndices(),o=selected();$('properties').insertAdjacentHTML('beforeend',`<h3>Manipuler · ${ids.length} objet(s)</h3><p class="note">Poignée orange : tourner · Alt pendant la rotation : libre.<br>Ctrl + clic : ajouter / retirer un objet ; cliquer le vide désélectionne.</p><button id="rotateMinus">↶ ${rotationIncrement||15}°</button><button id="rotatePlus">↷ ${rotationIncrement||15}°</button><label class="check"><input id="lockAspect" type="checkbox" ${o.lockAspect!==false?'checked':''}> Conserver les proportions</label><label class="check"><input id="lockObject" type="checkbox" ${o.locked?'checked':''}> Verrouiller la sélection</label><button id="nativeDimensions">Rétablir les dimensions du modèle</button><button id="groupSelection">Grouper</button><button id="ungroupSelection">Dégrouper</button><button id="alignX">Aligner les centres X</button><button id="alignZ">Aligner les centres Z</button><button id="distributeX">Répartir les centres X</button><button id="distributeZ">Répartir les centres Z</button>`);
 $('rotateMinus').onclick=()=>rotateFurniture(-(rotationIncrement||15)*Math.PI/180);$('rotatePlus').onclick=()=>rotateFurniture((rotationIncrement||15)*Math.PI/180);$('groupSelection').onclick=groupFurniture;$('ungroupSelection').onclick=()=>commit(()=>{requireUnlocked();ids.forEach(i=>delete state.furniture[i].groupId);selection={kind:'furniture',i:ids[0],indices:ids};});$('lockAspect').onchange=()=>commit(()=>ids.forEach(i=>state.furniture[i].lockAspect=$('lockAspect').checked));$('lockObject').onchange=()=>commit(()=>ids.forEach(i=>state.furniture[i].locked=$('lockObject').checked));$('nativeDimensions').onclick=restoreFurnitureSize;for(const axis of ['X','Z']){$('align'+axis).onclick=()=>alignFurniture(axis.toLowerCase());$('distribute'+axis).onclick=()=>distributeFurniture(axis.toLowerCase());}
}
function manipulationSetup(){
 $('tab-furniture').insertAdjacentHTML('afterbegin','<details open><summary>Placement &amp; rotation</summary><label class="field">Pas de rotation<select id="rotationIncrement"><option value="0">Libre</option><option value="15" selected>15°</option><option value="45">45°</option><option value="90">90°</option></select></label><label class="check"><input type="checkbox" id="repeatPlacement"> Poser plusieurs exemplaires</label><label class="check"><input type="checkbox" id="allowOverlap"> Placement libre malgré les collisions</label><p id="placementStatus" class="note"></p></details>');
 $('rotationIncrement').onchange=()=>{rotationIncrement=+$('rotationIncrement').value;properties();};$('repeatPlacement').onchange=()=>repeatPlacement=$('repeatPlacement').checked;$('allowOverlap').onchange=()=>allowOverlap=$('allowOverlap').checked;}
